### ISSUE TITLE
Deps Build failed on MacOs 10.12.6 (librsvg error)

### ISSUE THREAD

**Issue by aprouzeau** [libavg/libavg#802]
Hello,

Today I tried to install libavg on MacOs 10.12.6 following the instructions here: https://www.libavg.de/site/projects/libavg/wiki/MacSourceInstall

It failed in the build of the dependencies while installing librsvg-2.34.0

```bash
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
undef: _iconv_close
undef: _iconv
undef: _iconv_open
Undefined symbols for architecture x86_64:
  "_iconv_close", referenced from:
      _g_iconv_close in libglib-2.0.a(gconvert.o)
      _open_converter in libglib-2.0.a(gconvert.o)
      _close_converter in libglib-2.0.a(gconvert.o)
     (maybe you meant: _g_iconv_close)
  "_iconv", referenced from:
      _g_iconv in libglib-2.0.a(gconvert.o)
      _g_convert_with_iconv in libglib-2.0.a(gconvert.o)
      _open_converter in libglib-2.0.a(gconvert.o)
      _g_convert_with_fallback in libglib-2.0.a(gconvert.o)
      __nl_find_msg in libintl.a(dcigettext.o)
     (maybe you meant: _g_convert_with_iconv, _g_iconv , _g_iconv_open , _g_iconv_close )
  "_iconv_open", referenced from:
      _g_iconv_open in libglib-2.0.a(gconvert.o)
      __nl_find_msg in libintl.a(dcigettext.o)
     (maybe you meant: _g_iconv_open)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [rsvg-convert] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by uzadow** [comment]
I haven't seen that error, so I'll need to reproduce your config (which will probably involve installing 10.12 on an external ssd). I just checked, and one colleague has libavg installed and working on Mac OS X 10.13 here (but not 10.12). Also, no one (that I know of) has updated xcode command line tools to 9.0 yet, so that might cause the issue as well.

But: Before I do that, can you make sure that there are no foreign libraries on your system that might mess up the build? If you have brew, MacPorts or something similar installed, remove their directories from the path and run the dependencies build again. [1] points in that direction...

If that isn't the issue, I'll need to know which xcode version you have installed so I can try to reproduce things.

[1] https://stackoverflow.com/questions/12619600/libiconv-and-macos

**Comment by hth-** [comment]
I was able to build the dependencies on two different machines with OS X 10.12 installed.

Machine A:

```
$ sw_vers
> ProductVersion:	10.12.6

$ xcrun --sdk macosx --show-sdk-version
> 10.13

$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
> version: 9.1.0.0.1.1508540944
``` 

 Machine B:
 
```
$ sw_vers
> ProductVersion: 10.12.6

$ xcrun --sdk macosx --show-sdk-version
> 10.12

$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
> version: 8.3.2.0.1.1492020469
```

On machine B I could build the dependencies and libavg without an error.

On machine A I had to change the librsvg configure step in order to build the 
library. 

Please see the branch commit c41e799 and https://forums.developer.apple.com/thread/87829 for
reference.

**Comment by aprouzeau** [comment]
My first issue came from a library that was also installed by Macport. 

I removed Macport and I still get an error:

```bash
dyld: Library not loaded: @rpath/libxml2.2.dylib
  Referenced from: /Users/aprouzeau/Documents/Library/libavg/deps/librsvg-2.34.0/./conftest
  Reason: Incompatible library version: conftest requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
```

The configuration of my machine are very similar to machine A presented by hth so I will see the configure step you talked about:

```bash
$ sw_vers
> ProductVersion:	10.12.6

$ xcrun --sdk macosx --show-sdk-version
> 10.13

$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
> version: 9.0.0.0.1.1504363082
```

**Comment by uzadow** [comment]
Cool, we're a step further. Since it's failing in librsvg: Are you getting this error before or after applying hth's patch? If this is after applying the patch, make sure you don't have any other versions of libxml in the path:

    $ locate libxml2.2.dylib
    > /usr/lib/libxml2.2.dylib

**Comment by uzadow** [comment]
Closing this bug because there hasn't been any activity for a while.
@aprouzeau, feel free to re-open the bug if you have any new questions!
