### ISSUE TITLE
Ubuntu 12.04LTS build broken (libavresample version issue)

### ISSUE THREAD

**Issue by scotty007** [libavg/libavg#731]
Since the libavresample bug fix (commit 882c543) building libavg fails:
```
  CXX    FFMpegDemuxer.lo
In file included from FFMpegDemuxer.h:27:0,
                 from FFMpegDemuxer.cpp:22:
WrapFFMpeg.h:70:42: fatal error: libavresample/avresample.h: No such file or directory
```

Commit 0974e6d builds fine.

**Comment by uzadow** [comment]
This is a mess, because there seems to be no way of determining the API that's supported across all versions - libav does one thing, ffmpeg another. We have had three versions of this code and they all break on at least one configuration (look through the history to see the #defines we tried).

The one we have now seems to work on all systems except Ubuntu 12.04. How important is support for that platform?

**Comment by scotty007** [comment]
Hmm, it's my main development system. But this will change when 16.04LTS gets released. I guess I have to live with that issue until then. No idea how many other people are still using 14.04LTS.

**Comment by uzadow** [comment]
I found another user with 12.04, so I've reverted to a commit that should work. Can you test with Ubuntu 12.04?

Unfortunately, this breaks on newer systems, including Raspbian Jessie. I'm reopening #729.

**Comment by scotty007** [comment]
Yep, building on Ubuntu 12.04 works again. Thanks.
